# FLEET CONFIG =================================================================
rmf_fleet:
  name: "robot3_fleet"
  limits:
    linear: [0.55, 1.0]      # velocity [m/s], acceleration [m/s²]
    angular: [0.3, 1.0]      # angular velocity [rad/s], angular acceleration [rad/s²]
  profile:
    footprint: 0.7            # robot radius in meters
    vicinity: 0.7             # interaction vicinity radius in meters
  reversible: True
  battery_system:
    voltage: 12.0
    capacity: 24.0
    charging_current: 5.0
  mechanical_system:
    mass: 20.0
    moment_of_inertia: 10.0
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0
  tool_system:
    power: 0.0
  recharge_threshold: 0.10
  recharge_soc: 1.0
  publish_fleet_state: 10.0
  account_for_battery_drain: True
  task_capabilities:
    loop: True
    delivery: True
    clean: False
  finishing_request: "nothing" # [park, charge, nothing]
  responsive_wait: True
  robots:
    # robot1:
    #   charger: "robot1_charger"
    #   responsive_wait: False
    #   navigation_stack: 2
    #   init_timeout_sec: 10
    #   initial_map: "L1"
    #   service_call_timeout_sec: 1.0
    #   map_frame: "map"
    #   robot_frame: "base_footprint"
    #   maps:
    #     L1:
    #       map_url: "http://localhost:8080/new_map.yaml"
    #     initial_pose: [5.0, -4.0, -3.14]  
    robot3:
      charger: "robot3_charger"
      responsive_wait: False
      navigation_stack: 2
      init_timeout_sec: 10
      initial_map: "L1"
      service_call_timeout_sec: 1.0
      map_frame: "map"
      robot_frame: "base_footprint"
      maps:
        L1:
          map_url: "/home/siddhu/route_ws/src/bcr_bot/maps/new_map.yaml"
        initial_pose: [5.0, -13.0, 0.0]   
  robot_state_update_frequency: 10.0

# TRANSFORM CONFIG =============================================================
reference_coordinates:
  L1:
    rmf: [[0.0, 0.0], [0.0, -24.0], [24.0, 0.0], [24.0, -24.0]]
    robot: [[-12.0, 12.0], [-12.0, -12.0], [12.0, 12.0], [12.0, -12.0]]

# PLUGINS =======================================================================
plugins:
  hello_world:
    module: "free_fleet_examples.actions.hello_world"
    actions: ["hello_world", "delayed_hello_world"]
