# costmap_filter_info_server:
#   ros__parameters:
#     use_sim_time: true
#     type: 0
#     filter_info_topic: "/costmap_filter_info"
#     mask_topic: "/keepout_filter_mask"
#     base: 0.0
#     multiplier: 1.0
# filter_mask_server:
#   ros__parameters:
#     use_sim_time: true
#     frame_id: "map"
#     topic_name: "/keepout_filter_mask"
#     yaml_filename: "filter_map.yaml"

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: true
    type: 1
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/speed_filter_mask"
    base: 100.0
    multiplier: -1.0
filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/speed_filter_mask"
    yaml_filename: "hospital_map.yaml"






# costmap_filter_info_server:
#   ros__parameters:
#     use_sim_time: true
#     filter_info_topic: "/costmap_filter_info"

#     # You can specify any defaults here, theyâ€™ll be overridden by pixel values.
#     base: 0.0
#     multiplier: 1.0

#     # This will publish the mask topic (map image) with values used by both filters
#     mask_topic: "/filter_mask"

# filter_mask_server:
#   ros__parameters:
#     use_sim_time: true
#     frame_id: "map"
#     topic_name: "/filter_mask"
#     yaml_filename: "filter_map.yaml"


