twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_collision
        timeout : 0.5
        priority: 30
      # tracker:
      #   topic   : /cmd_vel_tracker
      #   timeout : 0.5
      #   priority: 20
      joystick:
        topic   : cmd_vel_teleop
        timeout : 0.5
        priority: 100

      # apriltag_relocalizer:
      #   topic   : /cmd_vel_tag
      #   timeout : 0.5
      #   priority: 10 
